name: Build
on:
   push:
     branches: [ 'main' ]
     paths-ignore: [ 'docs/**' ]

permissions: write-all

jobs:
  build:
    runs-on: macos-12
    env:
      SLN_FILE: NoSamples.sln
      VERSION: 2.1.0
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Read last version from CHANGELOG.md
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        path: ./CHANGELOG.md
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dotnet workload
      run: dotnet workload install maui
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} -p:Version=${VERSION}-nightly-${GITHUB_RUN_ID} --no-restore --configuration Release