name: Release
on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']
    paths-ignore: [ 'docs/**' ]

permissions: write-all

jobs:
  build:
    runs-on: macos-12
    environment: nuget
    env:
      SLN_FILE: NoSamples.sln
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
    - name: Set release version
      run: |
        if [ "${PRE_RELEASE}" == "" ]; then
          RELEASE_VERSION=${MAJOR}.${MINOR}.${PATCH}
        else
          RELEASE_VERSION=${MAJOR}.${MINOR}.${PATCH}-${PRE_RELEASE}
        fi
        echo "Release version is $RELEASE_VERSION"
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: ./CHANGELOG.md
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dotnet workload
      run: dotnet workload install maui
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} -p:Version="${MAJOR}.${MINOR}.${PATCH}" --no-restore --configuration Release
    # - name: Test
    #   run: dotnet test ${SLN_FILE} -p:Version="${MAJOR}.${MINOR}.${PATCH}" --no-build --configuration Release
    - name: Pack
      run: |
        dotnet pack ${SLN_FILE} -p:Version="${MAJOR}.${MINOR}.${PATCH}" --configuration Release --output nupkgs
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: nupkgs/
    - name: Push
      run: |
        dotnet nuget push "nupkgs/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate